
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.compi.formularios.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int POW = 38;
  public static final int MULT = 35;
  public static final int GE = 40;
  public static final int WIDTH = 15;
  public static final int ELEMENTS = 23;
  public static final int OPEN_QUESTION = 11;
  public static final int SEMI = 56;
  public static final int STYLES = 22;
  public static final int ORIENTATION = 25;
  public static final int FOR = 30;
  public static final int MINUS = 34;
  public static final int MULTIPLE_QUESTION = 14;
  public static final int POINTY = 18;
  public static final int POINTX = 17;
  public static final int DRAW = 32;
  public static final int NOT = 47;
  public static final int AND = 45;
  public static final int RANGE = 59;
  public static final int LT = 41;
  public static final int DROP_QUESTION = 12;
  public static final int RPAR = 49;
  public static final int OR = 46;
  public static final int IN = 31;
  public static final int COMMA = 54;
  public static final int SPECIAL_T = 7;
  public static final int DIV = 36;
  public static final int CORRECT = 21;
  public static final int PLUS = 33;
  public static final int ASSIGN = 57;
  public static final int IF = 26;
  public static final int DOT = 58;
  public static final int ID = 4;
  public static final int LE = 42;
  public static final int EOF = 0;
  public static final int TABLE = 9;
  public static final int error = 1;
  public static final int SELECT_QUESTION = 13;
  public static final int MOD = 37;
  public static final int NUMBER = 2;
  public static final int HEIGHT = 16;
  public static final int EQ = 43;
  public static final int LBRACK = 50;
  public static final int COLON = 55;
  public static final int LBRACE = 52;
  public static final int ELSE = 27;
  public static final int CONTENT = 24;
  public static final int WHO_IS_THAT_POKEMON = 60;
  public static final int RBRACK = 51;
  public static final int WHILE = 28;
  public static final int RBRACE = 53;
  public static final int NE = 44;
  public static final int LPAR = 48;
  public static final int STRING = 3;
  public static final int TEXT = 10;
  public static final int SECTION = 8;
  public static final int LABEL = 19;
  public static final int NUMBER_T = 5;
  public static final int GT = 39;
  public static final int STRING_T = 6;
  public static final int OPTIONS = 20;
  public static final int DO = 29;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NUMBER",
  "STRING",
  "ID",
  "NUMBER_T",
  "STRING_T",
  "SPECIAL_T",
  "SECTION",
  "TABLE",
  "TEXT",
  "OPEN_QUESTION",
  "DROP_QUESTION",
  "SELECT_QUESTION",
  "MULTIPLE_QUESTION",
  "WIDTH",
  "HEIGHT",
  "POINTX",
  "POINTY",
  "LABEL",
  "OPTIONS",
  "CORRECT",
  "STYLES",
  "ELEMENTS",
  "CONTENT",
  "ORIENTATION",
  "IF",
  "ELSE",
  "WHILE",
  "DO",
  "FOR",
  "IN",
  "DRAW",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "MOD",
  "POW",
  "GT",
  "GE",
  "LT",
  "LE",
  "EQ",
  "NE",
  "AND",
  "OR",
  "NOT",
  "LPAR",
  "RPAR",
  "LBRACK",
  "RBRACK",
  "LBRACE",
  "RBRACE",
  "COMMA",
  "COLON",
  "SEMI",
  "ASSIGN",
  "DOT",
  "RANGE",
  "WHO_IS_THAT_POKEMON"
  };
}

