
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.compi.formularios.parserGuardado;

import java_cup.runtime.*;
import java.util.*;
import java.util.AbstractMap;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class ParserGuardado extends lr_parser {

 public final Class getSymbolContainer() {
    return symG.class;
}

  /** Default constructor. */
  @Deprecated
  public ParserGuardado() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public ParserGuardado(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public ParserGuardado(java_cup.runtime.Scanner s, SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\051\000\002\002\004\000\002\002\003\000\002\003" +
    "\004\000\002\003\003\000\002\004\003\000\002\004\003" +
    "\000\002\004\003\000\002\004\003\000\002\004\003\000" +
    "\002\004\003\000\002\004\003\000\002\005\013\000\002" +
    "\005\012\000\002\006\006\000\002\006\007\000\002\007" +
    "\022\000\002\007\021\000\002\010\017\000\002\014\004" +
    "\000\002\014\003\000\002\015\005\000\002\016\006\000" +
    "\002\016\005\000\002\011\015\000\002\011\014\000\002" +
    "\012\015\000\002\012\014\000\002\013\017\000\002\013" +
    "\016\000\002\017\005\000\002\017\003\000\002\020\005" +
    "\000\002\020\003\000\002\021\005\000\002\021\004\000" +
    "\002\022\004\000\002\022\003\000\002\023\005\000\002" +
    "\023\005\000\002\023\005\000\002\023\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\207\000\020\004\007\005\022\006\011\007\020\010" +
    "\023\011\016\012\017\001\002\000\026\002\ufffb\004\ufffb" +
    "\005\ufffb\006\ufffb\007\ufffb\010\ufffb\011\ufffb\012\ufffb\016" +
    "\ufffb\020\ufffb\001\002\000\026\002\ufffc\004\ufffc\005\ufffc" +
    "\006\ufffc\007\ufffc\010\ufffc\011\ufffc\012\ufffc\016\ufffc\020" +
    "\ufffc\001\002\000\026\002\ufff9\004\ufff9\005\ufff9\006\ufff9" +
    "\007\ufff9\010\ufff9\011\ufff9\012\ufff9\016\ufff9\020\ufff9\001" +
    "\002\000\004\050\201\001\002\000\022\002\000\004\007" +
    "\005\022\006\011\007\020\010\023\011\016\012\017\001" +
    "\002\000\004\050\155\001\002\000\004\002\154\001\002" +
    "\000\026\002\ufffa\004\ufffa\005\ufffa\006\ufffa\007\ufffa\010" +
    "\ufffa\011\ufffa\012\ufffa\016\ufffa\020\ufffa\001\002\000\026" +
    "\002\ufffd\004\ufffd\005\ufffd\006\ufffd\007\ufffd\010\ufffd\011" +
    "\ufffd\012\ufffd\016\ufffd\020\ufffd\001\002\000\024\002\ufffe" +
    "\004\ufffe\005\ufffe\006\ufffe\007\ufffe\010\ufffe\011\ufffe\012" +
    "\ufffe\016\ufffe\001\002\000\004\047\141\001\002\000\004" +
    "\047\121\001\002\000\004\050\072\001\002\000\026\002" +
    "\ufff7\004\ufff7\005\ufff7\006\ufff7\007\ufff7\010\ufff7\011\ufff7" +
    "\012\ufff7\016\ufff7\020\ufff7\001\002\000\004\047\065\001" +
    "\002\000\004\047\025\001\002\000\026\002\ufff8\004\ufff8" +
    "\005\ufff8\006\ufff8\007\ufff8\010\ufff8\011\ufff8\012\ufff8\016" +
    "\ufff8\020\ufff8\001\002\000\004\040\026\001\002\000\004" +
    "\041\027\001\002\000\004\047\031\001\002\000\006\040" +
    "\033\042\032\001\002\000\006\040\uffe3\042\uffe3\001\002" +
    "\000\004\040\035\001\002\000\004\047\034\001\002\000" +
    "\006\040\uffe4\042\uffe4\001\002\000\004\050\036\001\002" +
    "\000\004\036\037\001\002\000\006\013\042\027\040\001" +
    "\002\000\026\002\uffe9\004\uffe9\005\uffe9\006\uffe9\007\uffe9" +
    "\010\uffe9\011\uffe9\012\uffe9\016\uffe9\020\uffe9\001\002\000" +
    "\004\027\064\001\002\000\014\014\047\032\050\033\051" +
    "\034\043\035\045\001\002\000\004\047\062\001\002\000" +
    "\014\014\uffdd\032\uffdd\033\uffdd\034\uffdd\035\uffdd\001\002" +
    "\000\004\047\060\001\002\000\014\014\057\032\050\033" +
    "\051\034\043\035\045\001\002\000\016\015\uffdf\023\uffdf" +
    "\024\uffdf\027\uffdf\030\uffdf\031\uffdf\001\002\000\004\047" +
    "\054\001\002\000\004\047\052\001\002\000\004\036\053" +
    "\001\002\000\014\014\uffdb\032\uffdb\033\uffdb\034\uffdb\035" +
    "\uffdb\001\002\000\004\036\055\001\002\000\014\014\uffdc" +
    "\032\uffdc\033\uffdc\034\uffdc\035\uffdc\001\002\000\014\014" +
    "\uffde\032\uffde\033\uffde\034\uffde\035\uffde\001\002\000\016" +
    "\015\uffe0\023\uffe0\024\uffe0\027\uffe0\030\uffe0\031\uffe0\001" +
    "\002\000\004\036\061\001\002\000\014\014\uffd9\032\uffd9" +
    "\033\uffd9\034\uffd9\035\uffd9\001\002\000\004\036\063\001" +
    "\002\000\014\014\uffda\032\uffda\033\uffda\034\uffda\035\uffda" +
    "\001\002\000\026\002\uffea\004\uffea\005\uffea\006\uffea\007" +
    "\uffea\010\uffea\011\uffea\012\uffea\016\uffea\020\uffea\001\002" +
    "\000\004\036\066\001\002\000\006\013\042\024\067\001" +
    "\002\000\026\002\ufff4\004\ufff4\005\ufff4\006\ufff4\007\ufff4" +
    "\010\ufff4\011\ufff4\012\ufff4\016\ufff4\020\ufff4\001\002\000" +
    "\004\024\071\001\002\000\026\002\ufff3\004\ufff3\005\ufff3" +
    "\006\ufff3\007\ufff3\010\ufff3\011\ufff3\012\ufff3\016\ufff3\020" +
    "\ufff3\001\002\000\004\040\073\001\002\000\004\050\074" +
    "\001\002\000\004\040\075\001\002\000\004\050\076\001" +
    "\002\000\004\040\077\001\002\000\004\050\100\001\002" +
    "\000\004\036\101\001\002\000\004\015\102\001\002\000" +
    "\004\021\104\001\002\000\006\016\116\021\104\001\002" +
    "\000\004\017\107\001\002\000\006\016\uffee\021\uffee\001" +
    "\002\000\006\017\113\022\112\001\002\000\020\004\007" +
    "\005\022\006\011\007\020\010\023\011\016\012\017\001" +
    "\002\000\004\020\111\001\002\000\006\017\uffeb\022\uffeb" +
    "\001\002\000\006\016\uffed\021\uffed\001\002\000\020\004" +
    "\007\005\022\006\011\007\020\010\023\011\016\012\017" +
    "\001\002\000\004\020\115\001\002\000\006\017\uffec\022" +
    "\uffec\001\002\000\004\026\120\001\002\000\006\016\uffef" +
    "\021\uffef\001\002\000\026\002\ufff0\004\ufff0\005\ufff0\006" +
    "\ufff0\007\ufff0\010\ufff0\011\ufff0\012\ufff0\016\ufff0\020\ufff0" +
    "\001\002\000\004\040\122\001\002\000\004\041\123\001" +
    "\002\000\004\047\031\001\002\000\006\040\033\042\125" +
    "\001\002\000\004\040\126\001\002\000\004\043\127\001" +
    "\002\000\004\050\130\001\002\000\006\040\uffe1\044\uffe1" +
    "\001\002\000\006\040\133\044\132\001\002\000\004\036" +
    "\135\001\002\000\004\050\134\001\002\000\006\040\uffe2" +
    "\044\uffe2\001\002\000\006\013\042\031\136\001\002\000" +
    "\026\002\uffe5\004\uffe5\005\uffe5\006\uffe5\007\uffe5\010\uffe5" +
    "\011\uffe5\012\uffe5\016\uffe5\020\uffe5\001\002\000\004\031" +
    "\140\001\002\000\026\002\uffe6\004\uffe6\005\uffe6\006\uffe6" +
    "\007\uffe6\010\uffe6\011\uffe6\012\uffe6\016\uffe6\020\uffe6\001" +
    "\002\000\004\040\142\001\002\000\004\041\143\001\002" +
    "\000\004\047\031\001\002\000\006\040\033\042\145\001" +
    "\002\000\004\040\146\001\002\000\004\050\147\001\002" +
    "\000\004\036\150\001\002\000\006\013\042\030\151\001" +
    "\002\000\026\002\uffe7\004\uffe7\005\uffe7\006\uffe7\007\uffe7" +
    "\010\uffe7\011\uffe7\012\uffe7\016\uffe7\020\uffe7\001\002\000" +
    "\004\030\153\001\002\000\026\002\uffe8\004\uffe8\005\uffe8" +
    "\006\uffe8\007\uffe8\010\uffe8\011\uffe8\012\uffe8\016\uffe8\020" +
    "\uffe8\001\002\000\004\002\001\001\002\000\004\040\156" +
    "\001\002\000\004\050\157\001\002\000\004\040\160\001" +
    "\002\000\004\050\161\001\002\000\004\040\162\001\002" +
    "\000\004\050\163\001\002\000\004\040\164\001\002\000" +
    "\004\045\165\001\002\000\004\036\166\001\002\000\006" +
    "\013\042\015\167\001\002\000\020\004\007\005\022\006" +
    "\011\007\020\010\023\011\016\012\017\001\002\000\004" +
    "\015\171\001\002\000\020\004\007\005\022\006\011\007" +
    "\020\010\023\011\016\012\017\001\002\000\022\004\007" +
    "\005\022\006\011\007\020\010\023\011\016\012\017\016" +
    "\174\001\002\000\024\002\uffff\004\uffff\005\uffff\006\uffff" +
    "\007\uffff\010\uffff\011\uffff\012\uffff\016\uffff\001\002\000" +
    "\004\025\175\001\002\000\026\002\ufff2\004\ufff2\005\ufff2" +
    "\006\ufff2\007\ufff2\010\ufff2\011\ufff2\012\ufff2\016\ufff2\020" +
    "\ufff2\001\002\000\022\004\007\005\022\006\011\007\020" +
    "\010\023\011\016\012\017\016\177\001\002\000\004\025" +
    "\200\001\002\000\026\002\ufff1\004\ufff1\005\ufff1\006\ufff1" +
    "\007\ufff1\010\ufff1\011\ufff1\012\ufff1\016\ufff1\020\ufff1\001" +
    "\002\000\004\040\202\001\002\000\004\050\203\001\002" +
    "\000\004\040\204\001\002\000\004\047\205\001\002\000" +
    "\004\036\206\001\002\000\006\013\042\023\210\001\002" +
    "\000\004\023\211\001\002\000\026\002\ufff5\004\ufff5\005" +
    "\ufff5\006\ufff5\007\ufff5\010\ufff5\011\ufff5\012\ufff5\016\ufff5" +
    "\020\ufff5\001\002\000\026\002\ufff6\004\ufff6\005\ufff6\006" +
    "\ufff6\007\ufff6\010\ufff6\011\ufff6\012\ufff6\016\ufff6\020\ufff6" +
    "\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\207\000\026\002\011\003\007\004\014\005\013\006" +
    "\004\007\003\010\012\011\005\012\023\013\020\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\022\004\172\005\013\006\004\007\003" +
    "\010\012\011\005\012\023\013\020\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\017\027\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\021\040" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\022" +
    "\045\023\043\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\023\055\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\021\067\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\014\102\015\104\001\001\000\004" +
    "\015\116\001\001\000\004\016\105\001\001\000\002\001" +
    "\001\000\002\001\001\000\022\004\107\005\013\006\004" +
    "\007\003\010\012\011\005\012\023\013\020\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\022" +
    "\004\113\005\013\006\004\007\003\010\012\011\005\012" +
    "\023\013\020\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\017\123\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\020\130\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\021\136\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\017\143\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\021\151\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\021\167\001\001\000\024\003\175\004\014" +
    "\005\013\006\004\007\003\010\012\011\005\012\023\013" +
    "\020\001\001\000\002\001\001\000\024\003\171\004\014" +
    "\005\013\006\004\007\003\010\012\011\005\012\023\013" +
    "\020\001\001\000\022\004\172\005\013\006\004\007\003" +
    "\010\012\011\005\012\023\013\020\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\022\004\172" +
    "\005\013\006\004\007\003\010\012\011\005\012\023\013" +
    "\020\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\021\206\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$ParserGuardado$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$ParserGuardado$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public Symbol do_action(
    int                        act_num,
    lr_parser parser,
    Stack            stack,
    int                        top)
    throws Exception
  {
    /* call code in generated class */
    return action_obj.CUP$ParserGuardado$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    private List<String> syntaxErrors = new ArrayList<>();

    public List<String> getSyntaxErrors(){
        return syntaxErrors;
    }

    private Map<String, Object> buildElement(String type, Map<String, Object> attrs){
        Map<String, Object> element = new HashMap<>();
        element.put("type", type);
        element.put("attrs", attrs);
        return element;
    }

    public double getSafeDouble(Object val, double def) {
        if (val == null) return def;
        try {
            double num = Double.parseDouble(val.toString());
            return num <= 0 ? def : num;
        } catch (Exception e) {
            return def;
        }
    }

    @Override
    public void syntax_error(Symbol s) {
        String token = (s.value == null) ? "EOF" : s.value.toString();
        syntaxErrors.add("Error Sintáctico en Guardado - Token: " + token +
            " Línea: " + s.left +
            " Columna: " + s.right
        );
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$ParserGuardado$actions {
  private final ParserGuardado parser;

  /** Constructor */
  CUP$ParserGuardado$actions(ParserGuardado parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final Symbol CUP$ParserGuardado$do_action_part00000000(
    int                        CUP$ParserGuardado$act_num,
    lr_parser CUP$ParserGuardado$parser,
    Stack            CUP$ParserGuardado$stack,
    int                        CUP$ParserGuardado$top)
    throws Exception
    {
      /* Symbol object for return from actions */
      Symbol CUP$ParserGuardado$result;

      /* select the action based on the action number */
      switch (CUP$ParserGuardado$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= pkm_file EOF 
            {
              Object RESULT =null;
		int start_valleft = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-1)).left;
		int start_valright = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-1)).right;
		List<Map<String,Object>> start_val = (List<Map<String,Object>>)((Symbol) CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-1)).value;
		RESULT = start_val;
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("$START",0, ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-1)), ((Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$ParserGuardado$parser.done_parsing();
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // pkm_file ::= element_list 
            {
              List<Map<String,Object>> RESULT =null;
		int elleft = ((Symbol)CUP$ParserGuardado$stack.peek()).left;
		int elright = ((Symbol)CUP$ParserGuardado$stack.peek()).right;
		List<Map<String,Object>> el = (List<Map<String,Object>>)((Symbol) CUP$ParserGuardado$stack.peek()).value;
		 RESULT = el; 
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("pkm_file",0, ((Symbol)CUP$ParserGuardado$stack.peek()), ((Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // element_list ::= element_list element 
            {
              List<Map<String,Object>> RESULT =null;
		int listleft = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-1)).left;
		int listright = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-1)).right;
		List<Map<String,Object>> list = (List<Map<String,Object>>)((Symbol) CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-1)).value;
		int eleft = ((Symbol)CUP$ParserGuardado$stack.peek()).left;
		int eright = ((Symbol)CUP$ParserGuardado$stack.peek()).right;
		Map<String,Object> e = (Map<String,Object>)((Symbol) CUP$ParserGuardado$stack.peek()).value;
		 list.add(e); RESULT = list; 
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("element_list",1, ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-1)), ((Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // element_list ::= element 
            {
              List<Map<String,Object>> RESULT =null;
		int eleft = ((Symbol)CUP$ParserGuardado$stack.peek()).left;
		int eright = ((Symbol)CUP$ParserGuardado$stack.peek()).right;
		Map<String,Object> e = (Map<String,Object>)((Symbol) CUP$ParserGuardado$stack.peek()).value;
		 List<Map<String, Object>> list = new ArrayList<>(); list.add(e); RESULT = list; 
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("element_list",1, ((Symbol)CUP$ParserGuardado$stack.peek()), ((Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // element ::= text_item 
            {
              Map<String,Object> RESULT =null;
		int tleft = ((Symbol)CUP$ParserGuardado$stack.peek()).left;
		int tright = ((Symbol)CUP$ParserGuardado$stack.peek()).right;
		Map<String,Object> t = (Map<String,Object>)((Symbol) CUP$ParserGuardado$stack.peek()).value;
		 RESULT = t; 
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("element",2, ((Symbol)CUP$ParserGuardado$stack.peek()), ((Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // element ::= open_item 
            {
              Map<String,Object> RESULT =null;
		int oleft = ((Symbol)CUP$ParserGuardado$stack.peek()).left;
		int oright = ((Symbol)CUP$ParserGuardado$stack.peek()).right;
		Map<String,Object> o = (Map<String,Object>)((Symbol) CUP$ParserGuardado$stack.peek()).value;
		 RESULT = o; 
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("element",2, ((Symbol)CUP$ParserGuardado$stack.peek()), ((Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // element ::= section_item 
            {
              Map<String,Object> RESULT =null;
		int sleft = ((Symbol)CUP$ParserGuardado$stack.peek()).left;
		int sright = ((Symbol)CUP$ParserGuardado$stack.peek()).right;
		Map<String,Object> s = (Map<String,Object>)((Symbol) CUP$ParserGuardado$stack.peek()).value;
		 RESULT = s; 
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("element",2, ((Symbol)CUP$ParserGuardado$stack.peek()), ((Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // element ::= table_item 
            {
              Map<String,Object> RESULT =null;
		int tbleft = ((Symbol)CUP$ParserGuardado$stack.peek()).left;
		int tbright = ((Symbol)CUP$ParserGuardado$stack.peek()).right;
		Map<String,Object> tb = (Map<String,Object>)((Symbol) CUP$ParserGuardado$stack.peek()).value;
		 RESULT = tb; 
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("element",2, ((Symbol)CUP$ParserGuardado$stack.peek()), ((Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // element ::= select_item 
            {
              Map<String,Object> RESULT =null;
		int slleft = ((Symbol)CUP$ParserGuardado$stack.peek()).left;
		int slright = ((Symbol)CUP$ParserGuardado$stack.peek()).right;
		Map<String,Object> sl = (Map<String,Object>)((Symbol) CUP$ParserGuardado$stack.peek()).value;
		 RESULT = sl; 
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("element",2, ((Symbol)CUP$ParserGuardado$stack.peek()), ((Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // element ::= drop_item 
            {
              Map<String,Object> RESULT =null;
		int dleft = ((Symbol)CUP$ParserGuardado$stack.peek()).left;
		int dright = ((Symbol)CUP$ParserGuardado$stack.peek()).right;
		Map<String,Object> d = (Map<String,Object>)((Symbol) CUP$ParserGuardado$stack.peek()).value;
		 RESULT = d; 
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("element",2, ((Symbol)CUP$ParserGuardado$stack.peek()), ((Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // element ::= multiple_item 
            {
              Map<String,Object> RESULT =null;
		int mleft = ((Symbol)CUP$ParserGuardado$stack.peek()).left;
		int mright = ((Symbol)CUP$ParserGuardado$stack.peek()).right;
		Map<String,Object> m = (Map<String,Object>)((Symbol) CUP$ParserGuardado$stack.peek()).value;
		 RESULT = m; 
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("element",2, ((Symbol)CUP$ParserGuardado$stack.peek()), ((Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // text_item ::= TK_O_TEXT TK_NUMBER TK_COMMA TK_NUMBER TK_COMMA TK_STRING TK_ANGLE_RIGHT style_block TK_C_TEXT 
            {
              Map<String,Object> RESULT =null;
		int xleft = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-7)).left;
		int xright = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-7)).right;
		String x = (String)((Symbol) CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-7)).value;
		int yleft = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-5)).left;
		int yright = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-5)).right;
		String y = (String)((Symbol) CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-5)).value;
		int cleft = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-3)).left;
		int cright = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-3)).right;
		String c = (String)((Symbol) CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-3)).value;
		int stleft = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-1)).left;
		int stright = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-1)).right;
		Map<String,Object> st = (Map<String,Object>)((Symbol) CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-1)).value;
		 
        Map<String, Object> attrs = new HashMap<>();
        attrs.put("CONTENT", c);
        attrs.put("POINTX", parser.getSafeDouble(x, 10.0));
        attrs.put("POINTY", parser.getSafeDouble(y, 10.0));
        attrs.put("WIDTH", 350.0);
        attrs.put("HEIGHT", 80.0);
        attrs.put("STYLES", st);
        RESULT = parser.buildElement("TEXT", attrs); 
    
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("text_item",3, ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-8)), ((Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // text_item ::= TK_O_TEXT TK_NUMBER TK_COMMA TK_NUMBER TK_COMMA TK_STRING TK_ANGLE_RIGHT TK_C_TEXT 
            {
              Map<String,Object> RESULT =null;
		int xleft = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-6)).left;
		int xright = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-6)).right;
		String x = (String)((Symbol) CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-6)).value;
		int yleft = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-4)).left;
		int yright = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-4)).right;
		String y = (String)((Symbol) CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-4)).value;
		int cleft = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)).left;
		int cright = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)).right;
		String c = (String)((Symbol) CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)).value;
		 
        Map<String, Object> attrs = new HashMap<>();
        attrs.put("CONTENT", c);
        attrs.put("POINTX", parser.getSafeDouble(x, 10.0));
        attrs.put("POINTY", parser.getSafeDouble(y, 10.0));
        attrs.put("WIDTH", 350.0);
        attrs.put("HEIGHT", 80.0);
        RESULT = parser.buildElement("TEXT", attrs); 
    
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("text_item",3, ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-7)), ((Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // open_item ::= TK_O_OPEN TK_STRING TK_ANGLE_RIGHT TK_C_OPEN 
            {
              Map<String,Object> RESULT =null;
		int lblleft = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)).left;
		int lblright = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)).right;
		String lbl = (String)((Symbol) CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)).value;
		 
        Map<String, Object> attrs = new HashMap<>();
        attrs.put("LABEL", lbl);
        attrs.put("WIDTH", 350.0);
        attrs.put("HEIGHT", 80.0);
        RESULT = parser.buildElement("OPEN", attrs); 
    
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("open_item",4, ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-3)), ((Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // open_item ::= TK_O_OPEN TK_STRING TK_ANGLE_RIGHT style_block TK_C_OPEN 
            {
              Map<String,Object> RESULT =null;
		int lblleft = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-3)).left;
		int lblright = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-3)).right;
		String lbl = (String)((Symbol) CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-3)).value;
		 
        Map<String, Object> attrs = new HashMap<>();
        attrs.put("LABEL", lbl);
        attrs.put("WIDTH", 350.0);
        attrs.put("HEIGHT", 80.0);
        RESULT = parser.buildElement("OPEN", attrs); 
    
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("open_item",4, ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-4)), ((Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // section_item ::= TK_O_SECTION TK_NUMBER TK_COMMA TK_NUMBER TK_COMMA TK_NUMBER TK_COMMA TK_NUMBER TK_COMMA TK_VERTICAL TK_ANGLE_RIGHT style_block TK_O_CONTENT element_list TK_C_CONTENT TK_C_SECTION 
            {
              Map<String,Object> RESULT =null;
		int wleft = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-14)).left;
		int wright = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-14)).right;
		String w = (String)((Symbol) CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-14)).value;
		int hleft = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-12)).left;
		int hright = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-12)).right;
		String h = (String)((Symbol) CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-12)).value;
		int xleft = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-10)).left;
		int xright = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-10)).right;
		String x = (String)((Symbol) CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-10)).value;
		int yleft = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-8)).left;
		int yright = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-8)).right;
		String y = (String)((Symbol) CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-8)).value;
		int elleft = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)).left;
		int elright = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)).right;
		List<Map<String,Object>> el = (List<Map<String,Object>>)((Symbol) CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)).value;
		 
        Map<String, Object> attrs = new HashMap<>();
        attrs.put("WIDTH", parser.getSafeDouble(w, 380.0));
        attrs.put("HEIGHT", parser.getSafeDouble(h, 400.0));
        attrs.put("POINTX", parser.getSafeDouble(x, 10.0));
        attrs.put("POINTY", parser.getSafeDouble(y, 130.0));
        attrs.put("ORIENTATION", "VERTICAL");
        attrs.put("ELEMENTS", el);
        RESULT = parser.buildElement("SECTION", attrs); 
    
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("section_item",5, ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-15)), ((Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // section_item ::= TK_O_SECTION TK_NUMBER TK_COMMA TK_NUMBER TK_COMMA TK_NUMBER TK_COMMA TK_NUMBER TK_COMMA TK_VERTICAL TK_ANGLE_RIGHT TK_O_CONTENT element_list TK_C_CONTENT TK_C_SECTION 
            {
              Map<String,Object> RESULT =null;
		int wleft = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-13)).left;
		int wright = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-13)).right;
		String w = (String)((Symbol) CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-13)).value;
		int hleft = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-11)).left;
		int hright = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-11)).right;
		String h = (String)((Symbol) CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-11)).value;
		int xleft = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-9)).left;
		int xright = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-9)).right;
		String x = (String)((Symbol) CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-9)).value;
		int yleft = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-7)).left;
		int yright = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-7)).right;
		String y = (String)((Symbol) CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-7)).value;
		int elleft = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)).left;
		int elright = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)).right;
		List<Map<String,Object>> el = (List<Map<String,Object>>)((Symbol) CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)).value;
		 
        Map<String, Object> attrs = new HashMap<>();
        attrs.put("WIDTH", parser.getSafeDouble(w, 380.0));
        attrs.put("HEIGHT", parser.getSafeDouble(h, 400.0));
        attrs.put("POINTX", parser.getSafeDouble(x, 10.0));
        attrs.put("POINTY", parser.getSafeDouble(y, 130.0));
        attrs.put("ORIENTATION", "VERTICAL");
        attrs.put("ELEMENTS", el);
        RESULT = parser.buildElement("SECTION", attrs); 
    
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("section_item",5, ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-14)), ((Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // table_item ::= TK_O_TABLE TK_NUMBER TK_COMMA TK_NUMBER TK_COMMA TK_NUMBER TK_COMMA TK_NUMBER TK_ANGLE_RIGHT TK_O_CONTENT table_lines TK_C_CONTENT TK_C_TABLE 
            {
              Map<String,Object> RESULT =null;
		int wleft = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-11)).left;
		int wright = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-11)).right;
		String w = (String)((Symbol) CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-11)).value;
		int hleft = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-9)).left;
		int hright = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-9)).right;
		String h = (String)((Symbol) CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-9)).value;
		int xleft = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-7)).left;
		int xright = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-7)).right;
		String x = (String)((Symbol) CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-7)).value;
		int yleft = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-5)).left;
		int yright = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-5)).right;
		String y = (String)((Symbol) CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-5)).value;
		int linesleft = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)).left;
		int linesright = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)).right;
		List<List<Map<String,Object>>> lines = (List<List<Map<String,Object>>>)((Symbol) CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)).value;
		 
        Map<String, Object> attrs = new HashMap<>();
        attrs.put("WIDTH", parser.getSafeDouble(w, 380.0));
        attrs.put("HEIGHT", parser.getSafeDouble(h, 300.0));
        attrs.put("POINTX", parser.getSafeDouble(x, 10.0));
        attrs.put("POINTY", parser.getSafeDouble(y, 10.0));
        attrs.put("ELEMENTS", lines);
        RESULT = parser.buildElement("TABLE", attrs); 
    
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("table_item",6, ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-12)), ((Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // table_lines ::= table_lines table_line 
            {
              List<List<Map<String,Object>>> RESULT =null;
		int listleft = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-1)).left;
		int listright = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-1)).right;
		List<List<Map<String,Object>>> list = (List<List<Map<String,Object>>>)((Symbol) CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-1)).value;
		int lleft = ((Symbol)CUP$ParserGuardado$stack.peek()).left;
		int lright = ((Symbol)CUP$ParserGuardado$stack.peek()).right;
		List<Map<String,Object>> l = (List<Map<String,Object>>)((Symbol) CUP$ParserGuardado$stack.peek()).value;
		 list.add(l); RESULT = list; 
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("table_lines",10, ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-1)), ((Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // table_lines ::= table_line 
            {
              List<List<Map<String,Object>>> RESULT =null;
		int lleft = ((Symbol)CUP$ParserGuardado$stack.peek()).left;
		int lright = ((Symbol)CUP$ParserGuardado$stack.peek()).right;
		List<Map<String,Object>> l = (List<Map<String,Object>>)((Symbol) CUP$ParserGuardado$stack.peek()).value;
		 List<List<Map<String, Object>>> list = new ArrayList<>(); list.add(l); RESULT = list; 
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("table_lines",10, ((Symbol)CUP$ParserGuardado$stack.peek()), ((Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // table_line ::= TK_O_LINE inner_elements TK_C_LINE 
            {
              List<Map<String,Object>> RESULT =null;
		int elleft = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-1)).left;
		int elright = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-1)).right;
		List<Map<String,Object>> el = (List<Map<String,Object>>)((Symbol) CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-1)).value;
		 RESULT = el; 
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("table_line",11, ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // inner_elements ::= inner_elements TK_O_ELEMENT element TK_C_ELEMENT 
            {
              List<Map<String,Object>> RESULT =null;
		int listleft = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-3)).left;
		int listright = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-3)).right;
		List<Map<String,Object>> list = (List<Map<String,Object>>)((Symbol) CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-3)).value;
		int eleft = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-1)).left;
		int eright = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-1)).right;
		Map<String,Object> e = (Map<String,Object>)((Symbol) CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-1)).value;
		 list.add(e); RESULT = list; 
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("inner_elements",12, ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-3)), ((Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // inner_elements ::= TK_O_ELEMENT element TK_C_ELEMENT 
            {
              List<Map<String,Object>> RESULT =null;
		int eleft = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-1)).left;
		int eright = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-1)).right;
		Map<String,Object> e = (Map<String,Object>)((Symbol) CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-1)).value;
		 List<Map<String, Object>> list = new ArrayList<>(); list.add(e); RESULT = list; 
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("inner_elements",12, ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // select_item ::= TK_O_SELECT TK_STRING TK_COMMA TK_LBRACE string_list TK_RBRACE TK_COMMA TK_NUMBER TK_ANGLE_RIGHT style_block TK_C_SELECT 
            {
              Map<String,Object> RESULT =null;
		int lblleft = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-9)).left;
		int lblright = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-9)).right;
		String lbl = (String)((Symbol) CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-9)).value;
		int optsleft = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-6)).left;
		int optsright = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-6)).right;
		List<String> opts = (List<String>)((Symbol) CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-6)).value;
		int ansleft = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-3)).left;
		int ansright = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-3)).right;
		String ans = (String)((Symbol) CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-3)).value;
		 
        Map<String, Object> attrs = new HashMap<>();
        attrs.put("LABEL", lbl);
        attrs.put("OPTIONS", opts);
        attrs.put("CORRECT", parser.getSafeDouble(ans, 0.0));
        attrs.put("WIDTH", 350.0);
        attrs.put("HEIGHT", 80.0);
        RESULT = parser.buildElement("SELECT", attrs); 
    
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("select_item",7, ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-10)), ((Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // select_item ::= TK_O_SELECT TK_STRING TK_COMMA TK_LBRACE string_list TK_RBRACE TK_COMMA TK_NUMBER TK_ANGLE_RIGHT TK_C_SELECT 
            {
              Map<String,Object> RESULT =null;
		int lblleft = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-8)).left;
		int lblright = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-8)).right;
		String lbl = (String)((Symbol) CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-8)).value;
		int optsleft = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-5)).left;
		int optsright = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-5)).right;
		List<String> opts = (List<String>)((Symbol) CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-5)).value;
		int ansleft = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)).left;
		int ansright = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)).right;
		String ans = (String)((Symbol) CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)).value;
		 
        Map<String, Object> attrs = new HashMap<>();
        attrs.put("LABEL", lbl);
        attrs.put("OPTIONS", opts);
        attrs.put("CORRECT", parser.getSafeDouble(ans, 0.0));
        attrs.put("WIDTH", 350.0);
        attrs.put("HEIGHT", 80.0);
        RESULT = parser.buildElement("SELECT", attrs); 
    
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("select_item",7, ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-9)), ((Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // drop_item ::= TK_O_DROP TK_STRING TK_COMMA TK_LBRACE string_list TK_RBRACE TK_COMMA TK_NUMBER TK_ANGLE_RIGHT style_block TK_C_DROP 
            {
              Map<String,Object> RESULT =null;
		int lblleft = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-9)).left;
		int lblright = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-9)).right;
		String lbl = (String)((Symbol) CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-9)).value;
		int optsleft = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-6)).left;
		int optsright = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-6)).right;
		List<String> opts = (List<String>)((Symbol) CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-6)).value;
		int ansleft = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-3)).left;
		int ansright = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-3)).right;
		String ans = (String)((Symbol) CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-3)).value;
		 
        Map<String, Object> attrs = new HashMap<>();
        attrs.put("LABEL", lbl);
        attrs.put("OPTIONS", opts);
        attrs.put("WIDTH", 350.0);
        attrs.put("HEIGHT", 80.0);
        RESULT = parser.buildElement("DROP", attrs); 
    
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("drop_item",8, ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-10)), ((Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // drop_item ::= TK_O_DROP TK_STRING TK_COMMA TK_LBRACE string_list TK_RBRACE TK_COMMA TK_NUMBER TK_ANGLE_RIGHT TK_C_DROP 
            {
              Map<String,Object> RESULT =null;
		int lblleft = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-8)).left;
		int lblright = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-8)).right;
		String lbl = (String)((Symbol) CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-8)).value;
		int optsleft = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-5)).left;
		int optsright = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-5)).right;
		List<String> opts = (List<String>)((Symbol) CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-5)).value;
		int ansleft = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)).left;
		int ansright = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)).right;
		String ans = (String)((Symbol) CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)).value;
		 
        Map<String, Object> attrs = new HashMap<>();
        attrs.put("LABEL", lbl);
        attrs.put("OPTIONS", opts);
        attrs.put("WIDTH", 350.0);
        attrs.put("HEIGHT", 80.0);
        RESULT = parser.buildElement("DROP", attrs); 
    
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("drop_item",8, ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-9)), ((Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // multiple_item ::= TK_O_MULTIPLE TK_STRING TK_COMMA TK_LBRACE string_list TK_RBRACE TK_COMMA TK_LBRACKET number_list TK_RBRACKET TK_ANGLE_RIGHT style_block TK_C_MULTIPLE 
            {
              Map<String,Object> RESULT =null;
		int lblleft = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-11)).left;
		int lblright = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-11)).right;
		String lbl = (String)((Symbol) CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-11)).value;
		int optsleft = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-8)).left;
		int optsright = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-8)).right;
		List<String> opts = (List<String>)((Symbol) CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-8)).value;
		int ansleft = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-4)).left;
		int ansright = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-4)).right;
		List<Double> ans = (List<Double>)((Symbol) CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-4)).value;
		 
        Map<String, Object> attrs = new HashMap<>();
        attrs.put("LABEL", lbl);
        attrs.put("OPTIONS", opts);
        attrs.put("CORRECT", ans);
        attrs.put("WIDTH", 350.0);
        attrs.put("HEIGHT", 80.0);
        RESULT = parser.buildElement("MULTIPLE", attrs); 
    
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("multiple_item",9, ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-12)), ((Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // multiple_item ::= TK_O_MULTIPLE TK_STRING TK_COMMA TK_LBRACE string_list TK_RBRACE TK_COMMA TK_LBRACKET number_list TK_RBRACKET TK_ANGLE_RIGHT TK_C_MULTIPLE 
            {
              Map<String,Object> RESULT =null;
		int lblleft = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-10)).left;
		int lblright = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-10)).right;
		String lbl = (String)((Symbol) CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-10)).value;
		int optsleft = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-7)).left;
		int optsright = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-7)).right;
		List<String> opts = (List<String>)((Symbol) CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-7)).value;
		int ansleft = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-3)).left;
		int ansright = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-3)).right;
		List<Double> ans = (List<Double>)((Symbol) CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-3)).value;
		 
        Map<String, Object> attrs = new HashMap<>();
        attrs.put("LABEL", lbl);
        attrs.put("OPTIONS", opts);
        attrs.put("CORRECT", ans);
        attrs.put("WIDTH", 350.0);
        attrs.put("HEIGHT", 80.0);
        RESULT = parser.buildElement("MULTIPLE", attrs); 
    
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("multiple_item",9, ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-11)), ((Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // string_list ::= string_list TK_COMMA TK_STRING 
            {
              List<String> RESULT =null;
		int listleft = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)).left;
		int listright = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)).right;
		List<String> list = (List<String>)((Symbol) CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)).value;
		int sleft = ((Symbol)CUP$ParserGuardado$stack.peek()).left;
		int sright = ((Symbol)CUP$ParserGuardado$stack.peek()).right;
		String s = (String)((Symbol) CUP$ParserGuardado$stack.peek()).value;
		 list.add(s); RESULT = list; 
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("string_list",13, ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // string_list ::= TK_STRING 
            {
              List<String> RESULT =null;
		int sleft = ((Symbol)CUP$ParserGuardado$stack.peek()).left;
		int sright = ((Symbol)CUP$ParserGuardado$stack.peek()).right;
		String s = (String)((Symbol) CUP$ParserGuardado$stack.peek()).value;
		 List<String> list = new ArrayList<>(); list.add(s); RESULT = list; 
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("string_list",13, ((Symbol)CUP$ParserGuardado$stack.peek()), ((Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // number_list ::= number_list TK_COMMA TK_NUMBER 
            {
              List<Double> RESULT =null;
		int listleft = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)).left;
		int listright = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)).right;
		List<Double> list = (List<Double>)((Symbol) CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)).value;
		int nleft = ((Symbol)CUP$ParserGuardado$stack.peek()).left;
		int nright = ((Symbol)CUP$ParserGuardado$stack.peek()).right;
		String n = (String)((Symbol) CUP$ParserGuardado$stack.peek()).value;
		 list.add(parser.getSafeDouble(n, 0.0)); RESULT = list; 
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("number_list",14, ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // number_list ::= TK_NUMBER 
            {
              List<Double> RESULT =null;
		int nleft = ((Symbol)CUP$ParserGuardado$stack.peek()).left;
		int nright = ((Symbol)CUP$ParserGuardado$stack.peek()).right;
		String n = (String)((Symbol) CUP$ParserGuardado$stack.peek()).value;
		 List<Double> list = new ArrayList<>(); list.add(parser.getSafeDouble(n, 0.0)); RESULT = list; 
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("number_list",14, ((Symbol)CUP$ParserGuardado$stack.peek()), ((Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // style_block ::= TK_O_STYLE style_list TK_C_STYLE 
            {
              Map<String,Object> RESULT =null;
		int slleft = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-1)).left;
		int slright = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-1)).right;
		Map<String,Object> sl = (Map<String,Object>)((Symbol) CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-1)).value;
		 RESULT = sl; 
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("style_block",15, ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // style_block ::= TK_O_STYLE TK_C_STYLE 
            {
              Map<String,Object> RESULT =null;
		 RESULT = new HashMap<String, Object>(); 
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("style_block",15, ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-1)), ((Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // style_list ::= style_list style_item 
            {
              Map<String,Object> RESULT =null;
		int sleft = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-1)).left;
		int sright = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-1)).right;
		Map<String,Object> s = (Map<String,Object>)((Symbol) CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-1)).value;
		int ileft = ((Symbol)CUP$ParserGuardado$stack.peek()).left;
		int iright = ((Symbol)CUP$ParserGuardado$stack.peek()).right;
		Map.Entry<String,Object> i = (Map.Entry<String,Object>)((Symbol) CUP$ParserGuardado$stack.peek()).value;
		
        s.put(i.getKey(), i.getValue());
        RESULT = s;
    
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("style_list",16, ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-1)), ((Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // style_list ::= style_item 
            {
              Map<String,Object> RESULT =null;
		int ileft = ((Symbol)CUP$ParserGuardado$stack.peek()).left;
		int iright = ((Symbol)CUP$ParserGuardado$stack.peek()).right;
		Map.Entry<String,Object> i = (Map.Entry<String,Object>)((Symbol) CUP$ParserGuardado$stack.peek()).value;
		
        Map<String, Object> map = new HashMap<>();
        map.put(i.getKey(), i.getValue());
        RESULT = map;
    
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("style_list",16, ((Symbol)CUP$ParserGuardado$stack.peek()), ((Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // style_item ::= TK_STYLE_COLOR TK_STRING TK_ANGLE_RIGHT 
            {
              Map.Entry<String,Object> RESULT =null;
		int sleft = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-1)).left;
		int sright = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-1)).right;
		String s = (String)((Symbol) CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-1)).value;
		 RESULT = new AbstractMap.SimpleEntry<>("color", s); 
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("style_item",17, ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // style_item ::= TK_STYLE_FONT TK_STRING TK_ANGLE_RIGHT 
            {
              Map.Entry<String,Object> RESULT =null;
		int sleft = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-1)).left;
		int sright = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-1)).right;
		String s = (String)((Symbol) CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-1)).value;
		 RESULT = new AbstractMap.SimpleEntry<>("font family", s); 
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("style_item",17, ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // style_item ::= TK_STYLE_SIZE TK_STRING TK_ANGLE_RIGHT 
            {
              Map.Entry<String,Object> RESULT =null;
		int sleft = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-1)).left;
		int sright = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-1)).right;
		String s = (String)((Symbol) CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-1)).value;
		 RESULT = new AbstractMap.SimpleEntry<>("text size", s); 
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("style_item",17, ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // style_item ::= TK_STYLE_BG TK_STRING TK_ANGLE_RIGHT 
            {
              Map.Entry<String,Object> RESULT =null;
		int sleft = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-1)).left;
		int sright = ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-1)).right;
		String s = (String)((Symbol) CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-1)).value;
		 RESULT = new AbstractMap.SimpleEntry<>("background color", s); 
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("style_item",17, ((Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$ParserGuardado$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final Symbol CUP$ParserGuardado$do_action(
    int                        CUP$ParserGuardado$act_num,
    lr_parser CUP$ParserGuardado$parser,
    Stack            CUP$ParserGuardado$stack,
    int                        CUP$ParserGuardado$top)
    throws Exception
    {
              return CUP$ParserGuardado$do_action_part00000000(
                               CUP$ParserGuardado$act_num,
                               CUP$ParserGuardado$parser,
                               CUP$ParserGuardado$stack,
                               CUP$ParserGuardado$top);
    }
}

}
