
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.compi.formularios.parserGuardado;

/** CUP generated class containing symbol constants. */
public class symG {
  /* terminals */
  public static final int TK_C_LINE = 16;
  public static final int TK_STYLE_SIZE = 26;
  public static final int TK_HORIZONTAL = 36;
  public static final int TK_COMMA = 30;
  public static final int TK_VERTICAL = 35;
  public static final int TK_O_LINE = 15;
  public static final int TK_RBRACKET = 34;
  public static final int TK_C_DROP = 22;
  public static final int TK_C_OPEN = 18;
  public static final int TK_O_MULTIPLE = 8;
  public static final int TK_C_TEXT = 17;
  public static final int TK_STYLE_COLOR = 24;
  public static final int TK_O_DROP = 7;
  public static final int TK_NUMBER = 38;
  public static final int TK_C_CONTENT = 12;
  public static final int TK_O_OPEN = 3;
  public static final int EOF = 0;
  public static final int TK_C_ELEMENT = 14;
  public static final int error = 1;
  public static final int TK_O_CONTENT = 11;
  public static final int TK_O_TEXT = 2;
  public static final int TK_C_TABLE = 20;
  public static final int TK_O_SELECT = 6;
  public static final int TK_O_TABLE = 5;
  public static final int TK_CLOSE_SELF = 29;
  public static final int TK_LBRACE = 31;
  public static final int TK_O_ELEMENT = 13;
  public static final int TK_STYLE_BG = 27;
  public static final int TK_C_SELECT = 21;
  public static final int TK_C_SECTION = 19;
  public static final int TK_RBRACE = 32;
  public static final int TK_O_SECTION = 4;
  public static final int TK_STRING = 37;
  public static final int TK_LBRACKET = 33;
  public static final int TK_STYLE_FONT = 25;
  public static final int TK_C_MULTIPLE = 23;
  public static final int TK_ANGLE_RIGHT = 28;
  public static final int TK_C_STYLE = 10;
  public static final int TK_O_STYLE = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TK_O_TEXT",
  "TK_O_OPEN",
  "TK_O_SECTION",
  "TK_O_TABLE",
  "TK_O_SELECT",
  "TK_O_DROP",
  "TK_O_MULTIPLE",
  "TK_O_STYLE",
  "TK_C_STYLE",
  "TK_O_CONTENT",
  "TK_C_CONTENT",
  "TK_O_ELEMENT",
  "TK_C_ELEMENT",
  "TK_O_LINE",
  "TK_C_LINE",
  "TK_C_TEXT",
  "TK_C_OPEN",
  "TK_C_SECTION",
  "TK_C_TABLE",
  "TK_C_SELECT",
  "TK_C_DROP",
  "TK_C_MULTIPLE",
  "TK_STYLE_COLOR",
  "TK_STYLE_FONT",
  "TK_STYLE_SIZE",
  "TK_STYLE_BG",
  "TK_ANGLE_RIGHT",
  "TK_CLOSE_SELF",
  "TK_COMMA",
  "TK_LBRACE",
  "TK_RBRACE",
  "TK_LBRACKET",
  "TK_RBRACKET",
  "TK_VERTICAL",
  "TK_HORIZONTAL",
  "TK_STRING",
  "TK_NUMBER"
  };
}

